### ISSUE TITLE
Angular 15: Cannot find name 'Buffer' - quagga

### ISSUE THREAD

**Issue by ShadowQueen** [eisberg-labs/angular-components#5]
Hi,

I am trying to use the library ( "@eisberg-labs/ngx-barcode-scanner": "^5.0.0") with Angular 15 - the screenshot for angular CLI settings is below.
ng serve is not working because I am getting the error from quagga - error description below:

node_modules/@ericblade/quagga2/type-definitions/quagga.d.ts:784:33 - error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.

**To Reproduce**
1. Use Angular version 15.0.4 with library @eisberg-labs/ngx-barcode-scanner": "^5.0.0, and "@types/node": "^12.11.1",
2. npm install
3. ng s
4. Error for quagga  will be there 

**Expected behavior**
Able to run ng s and ng build without the error.

**Screenshots**

![image_2022_12_28T10_31_59_899Z](https://user-images.githubusercontent.com/16406109/209803950-f2ee53f9-2fbe-44f8-8a36-9e58ca4cdb53.png)

![image_2022_12_28T11_01_13_977Z](https://user-images.githubusercontent.com/16406109/209803545-97cb68b1-78fb-4d37-92f1-61a39fdb4b68.png)

 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Additional context**

**Comment by amarjanica** [comment]
Hi, thanks for using ngx-barcode-scanner! 

I added a working example at https://github.com/eisberg-labs/angular-components/tree/main/examples/ngx-barcode-scanner-basic. The one I previously shared https://codesandbox.io/embed/angular-15-ngx-barcode-scanner-w9btke seems to only work on codepen, and has some unnecessary deps.

Sorry for stupid question, but why do you need `@types/node` in your project?
Your app is running on the client right, not ssr?

If you still need to use `@types/node`, that version is a really old one.
If I'm not mistaken, types node major version corresponds to version of nodejs.
Since you're using node 14, install `@types/node@14.14.9`

Let me know if any of this helped you, tnx!

**Comment by ShadowQueen** [comment]
Hi,

Thank you for your quick response. Unfortunately, the advice did not help. I have tried to create the test app just with the module NgxBarcodeScannerModule, but that module can not be loaded.

I have attached just the app folder and package.json file, could not attach the whole project because it's exceeding the limits for upload.

Even tried a couple of times to do npm install and npm i --force, close VS studio - all the common stuff. But the module is not loaded.

I am missing something, any other suggestions?


[New folder.zip](https://github.com/eisberg-labs/angular-components/files/10344053/New.folder.zip)
![image_2023_01_04T12_34_52_884Z](https://user-images.githubusercontent.com/16406109/210556204-f516210e-a189-41ff-a33f-00380b276c90.png)

**Comment by amarjanica** [comment]
Can you create a public Github repository and share me the link? It will be easier if I can reproduce it.
Do you get the same error when trying to npm install?

In the meantime:
- maybe try `yarn` instead of `npm`
- try deleting the node_modules and reinstalling
- does the module at least show up in node_modules?

![Screenshot from 2023-01-04 13-45-59](https://user-images.githubusercontent.com/1394565/210558245-877fe609-fdd6-431c-a539-02ad765f5115.png)

**Comment by ShadowQueen** [comment]
Even tried deleting node modules and installing them again, the same situation.
The module is in node_modules
![image_2023_01_04T12_54_55_875Z](https://user-images.githubusercontent.com/16406109/210579350-7d7102ee-5b9d-496b-8960-89818da294d5.png)

Here is the repository: https://github.com/ShadowQueen/Barcode-Scanner

**Comment by amarjanica** [comment]
Thanks for sharing the code. Indeed it was my fault, I published it wrong, sorry about that.
Seems my example worked for me as I pulled from the github npm registry.
Try this, I confirm it works with your code but
```
"@eisberg-labs/ngx-barcode-scanner": "^5.0.2",
```

**Comment by ShadowQueen** [comment]
Now it's working. Thank you
